pip install numpy

In [2]:
import numpy as np

In [3]:
myList = [5,69,25,10]
arr = np.array(myList)

In [4]:
arr

array([ 5, 69, 25, 10])

In [5]:
arr.arange(5,2)

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [6]:
arr

array([ 5, 69, 25, 10])

In [7]:
arr.arange(0,25)
arr

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [8]:
np.arange(0,25)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
arr2 = np.arange(0,50)
println(arr2)

NameError: name 'println' is not defined

In [10]:
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [11]:
arr2.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [12]:
arr2[0:2,2:4]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [13]:
arr3 = arr2.reshape(0,100)
println(arr3)

ValueError: cannot reshape array of size 50 into shape (0,100)

In [14]:
print(arr3)

NameError: name 'arr3' is not defined

In [15]:
arr3 = arr2.reshape(0,100)

ValueError: cannot reshape array of size 50 into shape (0,100)

In [16]:
arr3 = np.arange(0,150,5)

In [17]:
arr3

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [18]:
arr3.shape

(30,)

In [19]:
arr3 = arr3.reshape(5,3)

ValueError: cannot reshape array of size 30 into shape (5,3)

In [20]:
arr3 = arr3.reshape(5,6)

In [21]:
arr3

array([[  0,   5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50,  55],
       [ 60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115],
       [120, 125, 130, 135, 140, 145]])

In [22]:
arr3[0:2,3:5]

array([[15, 20],
       [45, 50]])

In [23]:
arr3<100

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True, False, False, False, False],
       [False, False, False, False, False, False]])

In [24]:
result = arr3<100

In [25]:
typeOf(result)

NameError: name 'typeOf' is not defined

In [26]:
type(result)

numpy.ndarray

In [27]:
arr4 = arr3[arr3<100]

In [28]:
type(arr4)

numpy.ndarray

In [29]:
arr4

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])